version: "3.8"

services:
  servidor-central:
    build: .
    ports:
      - "5000:5000" # Puerto para clientes
      - "5001:5001" # Puerto para nodos trabajadores
    environment:
      - SERVER_PORT=5000
    networks:
      - bank-network

  nodo-trabajador-1:
    build: .
    command:
      [
        "java",
        "-cp",
        "bin",
        "NodoTrabajador",
        "1",
        "servidor-central",
        "5000",
        "/data/nodo1",
      ]
    volumes:
      - ./data/nodo1:/data/nodo1 # Mapear datos locales
    environment:
      - NODE_ID=1
    networks:
      - bank-network
    depends_on:
      - servidor-central

  nodo-trabajador-2:
    build: .
    command:
      [
        "java",
        "-cp",
        "bin",
        "NodoTrabajador",
        "2",
        "servidor-central",
        "5000",
        "/data/nodo2",
      ]
    volumes:
      - ./data/nodo2:/data/nodo2
    environment:
      - NODE_ID=2
    networks:
      - bank-network

  nodo-trabajador-3:
    build: .
    command:
      [
        "java",
        "-cp",
        "bin",
        "NodoTrabajador",
        "3",
        "servidor-central",
        "5000",
        "/data/nodo3",
      ]
    volumes:
      - ./data/nodo3:/data/nodo3
    environment:
      - NODE_ID=3
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge
